### PR TITLE
docs(examples): add gatsby example

### PR DESCRIPTION
**Pull request by spences10**
First Pass, let me know if there's anything needs changing!

Thanks

### CODE REVIEW

**Comment by notrab** [comment]
This is awesome @spences10 !

What are your thoughts on sourcing products from the filesystem through YAML or JSON to give a full Gatsby ecosystem feeling?

I've done this [here](https://github.com/CartQL/gatsby-cartql-starter/blob/3481c48bd864e9b358af4c7545430bb89966202c/src/gatsby/node/createPages.js) already which might provide a starting point.

Let me know what you think.

**Comment by spences10** [comment]
> This is awesome @spences10 !
> 
> What are your thoughts on sourcing products from the filesystem through YAML or JSON to give a full Gatsby ecosystem feeling?
> 
> I've done this [here](https://github.com/CartQL/gatsby-cartql-starter/blob/3481c48bd864e9b358af4c7545430bb89966202c/src/gatsby/node/createPages.js) already which might provide a starting point.
> 
> Let me know what you think.

So, use one of the files you've linked there and use that as the source for the `products` on the `Page` component?

**Comment by spences10** [comment]
Added a single file, no images, in line with the codesandbox example 👍

**Review by notrab — APPROVED** [review]

**Comment by notrab** [comment]
Looks great @spences10 🚀

**Comment by spences10** [comment]
> Looks great @spences10 🚀

I've moved it from draft, ready to merge @notrab 👍

**Pull request merged**
