### PR TITLE
feat: Add support for multiple item prices

### LINKED ISSUE #67: Handle multiple prices per item
I have a use case where I am implementing a localised cart where cart items may have a different prices per currency/locale.

Currently items are require to have a single `price: number`, which limits the possibility of offering multiple prices on cart items.

### PR DESCRIPTION
**Pull request by ynnoj**
Fixes #67.

- [ ] Update `calculateCartTotals`
- [ ] Update docs
- [ ] Test coverage

### CODE REVIEW

**Comment by notrab** [comment]
@ynnoj nice start!

I like the direction this is going, but this would indeed introduce a more verbose API for adding items (something I glossed over in #67 - and doesn't particularly bother me). It's now tied to the concept of currencies, whereas before it wasn't.

Perhaps your idea of conditional types is worth exploring, and would be backwards compatible. `price` would either be an integer or array... What do you think?

Happy to jump on a call to pair through this if you wanted.

**Comment by ynnoj** [comment]
> It's now tied to the concept of currencies, whereas before it wasn't.

I'm not sure this is actually an issue though seeing as though most payment processors will require currency info anyway.

**Comment by ynnoj** [comment]
Been thinking some more about this, particularly the conditional types and the impact that would have on the API and response.

Would anything prevent me adding multiple items with different price types? For example:

```js
[{
  id: '1',
  price: 200,
  quantity: 2
], {
  id: '2',
  price: [{
    currency: 'GBP',
    value: 100
  }, {
    currency: 'EUR',
    value: 150
  }]
}]
```

This would impact the `cartTotal` calculations as you'd end up with a total without a currency designation. Something like:

```js
[{
  currency: 'GBP',
  value: 100
}, {
  currency: 'EUR',
  value: 150
}, {
  value: 400
}]
```

**Comment by notrab** [comment]
@ynnoj you raise a good point on that. Let me think about it a bit more as well.

**Comment by ynnoj** [comment]
@notrab Any further thoughts on this?

**Comment by notrab** [comment]
I'll go ahead and close this for now as it's a bit stale and outdated but certainly something that someone could do more research on how we support this with a clean interface if there's enough interest.

**Pull request closed without merging**
