### PR TITLE
chore(funding): add sponsorship button

### PR DESCRIPTION
**Pull request by notrab**
Adds `FUNDING.yml` to enable sponsorships.

@ynnoj @getTobiasNielsen @craigtweedy get sponsorships setup, and we can get you added to the list.

### CODE REVIEW

**Comment by getTobiasNielsen** [comment]
Done.

**Comment by notrab** [comment]
@all-contributors please add @craigtweedy

**Comment by notrab** [comment]
@all-contributors please add @craigtweedy for code

**Comment by notrab** [comment]
@all-contributors please add @ynnoj for code

**Comment by notrab** [comment]
@all-contributors please add @spences10 for example

**Comment by notrab** [comment]
@all-contributors please add @spences10 for example

**Pull request merged**
